services:
  app:
    build:
      context: .
    environment:
      DATABASE_URL: /data/local.db
      HOST: 0.0.0.0
      NODE_ENV: production
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - app-data:/data

volumes:
  app-data:
